test:
	gcc *.c
	mkdir ../files/default/dir1/dir2/dir3/dir4/dir5/dirl6/dir7/dir8/dir9 -p
	mkdir ../files/user/ -p
	mkdir ../files/default/permission -p
	mkdir ../files/default/DirWithAllPossibleCharFile -p
del:
	rm a.out
	rm ../files/* -rf
